### ISSUE TITLE
How to build it

### ISSUE THREAD

**Issue by czadikem** [xanthousm/MCXR#5]
How do i build the jar for this?

**Comment by xanthousm** [comment]
If you want to build the .jar files yourself, you will have to set up a fabric modding environment (tutorial here: https://fabricmc.net/wiki/tutorial:setup). There are also general tutorials for building fabric mods online.

But if you just want to test the mod, you can get the jar files from the releases page under "assets": https://github.com/xanthousm/MCXR/releases
